title: Chenyu Yuan's Homepage
page-top-title: Chenyu Yuan
top-section-bg-text: Computer Science
home-subtitle: Chenyu Yuan&ensp;|&ensp;苑晨宇
copyright-text: '&copy; Chenyu Yuan 2023-2025. All Rights Reserved.'
